homework_06/forms/places.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, FloatField
from wtforms.validators import InputRequired, Length, NumberRange, ValidationError

from models import Place


class AddPlaceForm(FlaskForm):
    name_place = StringField('Название', validators=[InputRequired(), Length(5, 50)])
    description = TextAreaField('Детальное описание', validators=[InputRequired(), Length(100, 1550)])
    category = SelectField('Категория', coerce=int)
    city = SelectField('Город', coerce=int)
    rate = FloatField('Ваша оценка по 10 бальной шкале',
                      validators=[InputRequired(), NumberRange(min=0, max=10)])
    submit = SubmitField('Создать')

    def validate_name_place(self, name_place):
        if Place.query.filter_by(name_place=name_place.data).first():
            raise ValidationError('Место с таким наванием уже существует')

homework_06/views/places.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user

from forms.places import AddPlaceForm
from models.all_models import Place, Category, City
from models.database import db

places_app = Blueprint('places_app', __name__)


@places_app.get('/')
def places_list():
    places = Place.query.all()
    return render_template('places/place_list.html', places=places)


@places_app.get('/<int:place_id>')
# @login_required
def place_detail(place_id):
    place = Place.query.filter_by(id=place_id).first()
    return render_template('places/place_detail.html', place=place)


@places_app.get('/category/<int:cat_id>')
def places_by_category(cat_id):
    places = Place.query.join(Category).filter(Category.id == cat_id).all()
    return render_template('places/place_list.html', places=places)


@places_app.get('/city/<int:city_id>')
def places_by_city(city_id):
    places = Place.query.join(City).filter(City.id == city_id).all()
    return render_template('places/place_list.html', places=places)


@places_app.route('/create-place', methods=['POST', 'GET'])
# @login_required
def create_place():
    form = AddPlaceForm()
    categories = [(cat.id, cat.name_category) for cat in Category.query.all()]
    cities = [(city.id, city.name_city) for city in City.query.all()]
    form.category.choices = categories
    form.city.choices = cities
    if form.validate_on_submit():
        name_place = form.name_place.data
        description = form.description.data
        category = form.category.data
        # заглушка
        # author_id = current_user.id
        author_id = 4
        city_id = form.city.data
        rate = form.rate.data
        place = Place(name_place=name_place,
                      description=description,
                      category_id=category,
                      author_id=author_id,
                      city_id=city_id,
                      rate=rate)
        db.session.add(place)
        db.session.commit()
        return redirect(url_for('places_app.place_detail', place_id=place.id))
    return render_template('places/create_place.html', form=form)

homework_06/templates/places/create_place.html
{% extends 'base.html' %}

{% block title %}
    Создание записи
{% endblock %}

{% block content %}
        <form action="" method="post">
        {{ form.hidden_tag() }}
            <div class="container">
                {% if form.errors %}
                    {% for field, messages in form.errors.items() %}
                        <div class="alert alert-danger">
                            {{ form[field].label }}: {{ ', '.join(messages) }}
                        </div>
                    {% endfor %}
                {% endif %}

              <div class="form-group">
                  {{ form.name_place.label }}
                  {{ form.name_place(class="form-control") }}
              </div>

              <div class="form-group">
                  {{ form.description.label }}
                  {{ form.description(class="form-control") }}
              </div>

              <div class="form-group">
                  {{ form.category.label }}
                  {{ form.category(class="form-control") }}
              </div>

              <div class="form-group">
                  {{ form.city.label }}
                  {{ form.city(class="form-control") }}
              </div>

              <div class="form-group">
                  {{ form.rate.label }}
                  {{ form.rate(class="form-control") }}
              </div>

              <div class="container mt-3"><button type="submit" class="btn btn-primary">Submit</button></div>
            </div>
        </form>
{% endblock %}

homework_06/templates/places/place_detail.html
{% extends 'base.html' %}

{% block title %}
    Все места
{% endblock %}
{% block content %}
    {% if place %}
{#        {% if current_user.confirmed %}#}
            <div class="container mt-3" style="width: 40em">
                <div class="container mb-5">
                    <h3>{{ place.name_place }}</h3>
                </div>
                <div class="container mb-3">
                    <p>{{ place.description}}</p>
                </div>
                <div class="container mb-3">
                    <p>Дата создания поста: {{ place.created.strftime('%d-%m-%Y %H:%M') }}</p>
                </div>
                <div class="container mb-3">
                    <p>Рейтинг: {{ place.rate}}</p>
                </div>
            </div>
{#        {% else %}#}
{#            <div class="container mb-5">#}
{#                <h3>Для просмотра вам необходимо подтвердить свой email</h3>#}
{#            </div>#}
{#        {% endif %}#}
    {% else %}
        <div class="container mt-3">
            <h3>Такой записи не существует</h3>
        </div>
    {% endif %}
{% endblock %}

homework_06/templates/places/place_list.html
{% extends 'base.html' %}

{% block title %}
    Все места
{% endblock %}
{% block content %}
    {% if places %}
        {% for place in places %}
            <div class="container">
                <div class="card mb-5 mt-3" style="width: 18rem">
                  <div class="card-body" style="background-color: aquamarine">
                    <h5 class="card-title">{{ place.name_place }}</h5>
                    <p class="card-text">{{ place.description|truncate(100) }}</p>
                      <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{{ url_for('places_app.places_by_category', cat_id=place.category_id) }}">{{ place.category }}</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{{ url_for('places_app.places_by_city', city_id=place.city_id) }}">{{ place.city }}</a>
                        </li>
                      </ul>
                    <a href="{{ url_for('places_app.place_detail', place_id=place.id) }}" class="btn btn-primary">Читать</a>
                  </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="container mt-3">
            <h3>По данным параметрам запроса записи отсутствуют</h3>
        </div>
    {% endif %}
{% endblock %}