homework_06/views/places.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user

from forms.places import AddPlaceForm
from models.all_models import Place, Category, City
from models.database import db

places_app = Blueprint('places_app', __name__)


@places_app.get('/')
def places_list():
    places = Place.query.all()
    return render_template('places/place_list.html', places=places)


@places_app.get('/<int:place_id>')
# @login_required
def place_detail(place_id):
    place = Place.query.filter_by(id=place_id).first()
    return render_template('places/place_detail.html', place=place)


@places_app.get('/category/<int:cat_id>')
def places_by_category(cat_id):
    places = Place.query.join(Category).filter(Category.id == cat_id).all()
    return render_template('places/place_list.html', places=places)


@places_app.get('/city/<int:city_id>')
def places_by_city(city_id):
    places = Place.query.join(City).filter(City.id == city_id).all()
    return render_template('places/place_list.html', places=places)


@places_app.route('/create-place', methods=['POST', 'GET'])
# @login_required
def create_place():
    form = AddPlaceForm()
    categories = [(cat.id, cat.name_category) for cat in Category.query.all()]
    cities = [(city.id, city.name_city) for city in City.query.all()]
    form.category.choices = categories
    form.city.choices = cities
    if form.validate_on_submit():
        name_place = form.name_place.data
        description = form.description.data
        category = form.category.data
        # заглушка
        # author_id = current_user.id
        author_id = 4
        city_id = form.city.data
        rate = form.rate.data
        place = Place(name_place=name_place,
                      description=description,
                      category_id=category,
                      author_id=author_id,
                      city_id=city_id,
                      rate=rate)
        db.session.add(place)
        db.session.commit()
        return redirect(url_for('places_app.place_detail', place_id=place.id))
    return render_template('places/create_place.html', form=form)

homework_06/templates/about.html
{% extends 'base.html' %}

{% block title %}
    О нас
{% endblock %}
{% block content %}
    <div class="w-100 bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-dark overflow-hidden">
        <div class="col-md-10 p-lg-5 mx-auto my-5">
            <h1 class="display-3 fw-normal">Контакты</h1>
        </div>
        <div class="row">
            <div class="col-3">
                <p class="lead fw-normal">
                    Офис и производство находятся в Казани.
                    Дилерская сеть представлена более чем ста партнерами в более чем 20 странах мира. За подробной информацией о дилерской сети обращайтесь по телефону.
                </p>
            </div>
                <div class="col">
                    <p class="lead fw-normal">
                        +7(---)-----
                        some_nail@somemail.com
                    </p>
                </div>
        </div>
    </div>
{% endblock %}

homework_06/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
    {% block title %}
    {% endblock %}
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-link" href="{{ url_for('index') }}">Главная</a>
            <a class="nav-link" href={{ url_for('places_app.places_list') }}>Все места</a>
            {% if current_user.is_authenticated %}
                <a class="nav-link" href="#">Пользовaтель: {{ current_user.username }}</a>
                <a class="nav-link" href="{{ url_for('places_app.create_place') }}">Создать новые места</a>
                <a class="nav-link" href="{{ url_for('logout') }}">Выйти</a>
            {% else %}
                <a class="nav-link" href="{{ url_for('places_app.create_place') }}">Создать новые места</a>
{#            {% else %}#}
                <a class="nav-link" href="{{ url_for('register') }}">Регистрация</a>
                <a class="nav-link" href="{{ url_for('login') }}">Войти</a>
            {% endif %}
        </div>
      </div>
    </div>
  </nav>

    {% block content %}
    {% endblock %}

</body>
</html>

homework_06/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Главная
{% endblock %}
{% block content %}
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
            <h6 class="display-6 fw-normal">Любимые места для развлечений</h6>
        </div>
        <p class="lead fw-normal">
            На нашем сервисе Вы можете находить и создавать любые места для развлечений в Вашем городе.
        </p>
    </div>
{% endblock %}